re run script when failure

diff --git a/.github/workflows/courtreserve-advanced.yml b/.github/workflows/courtreserve-advanced.yml
--- a/.github/workflows/courtreserve-advanced.yml
+++ b/.github/workflows/courtreserve-advanced.yml
@@ -44,7 +44,10 @@ jobs:
           USERNAME: ${{ secrets.USERNAME }}
           PASSWORD: ${{ secrets.PASSWORD }}
         run: |
+        python courtreserve-advanced.py || {
+          echo "First run failed. Retrying..."
           python courtreserve-advanced.py
+        }
 
       - name: Upload logs (if any)
         if: always()
